import type {
  User,
  Question,
  Quiz,
  QuizAttempt,
  LeaderboardEntry,
} from "./mock-data-type";

// Mock Questions
export const mockQuestions: Question[] = [
  {
    id: "q1",
    text: "What is the capital of France?",
    options: ["London", "Berlin", "Paris", "Madrid"],
    correctAnswer: 2,
    category: "Geography",
    difficulty: "easy",
    points: 10,
  },
  {
    id: "q2",
    text: "Which planet is known as the Red Planet?",
    options: ["Venus", "Mars", "Jupiter", "Saturn"],
    correctAnswer: 1,
    category: "Science",
    difficulty: "easy",
    points: 10,
  },
  {
    id: "q3",
    text: "What is the largest mammal in the world?",
    options: ["African Elephant", "Blue Whale", "Giraffe", "Hippopotamus"],
    correctAnswer: 1,
    category: "Science",
    difficulty: "easy",
    points: 10,
  },
  {
    id: "q4",
    text: "In which year did World War II end?",
    options: ["1943", "1944", "1945", "1946"],
    correctAnswer: 2,
    category: "History",
    difficulty: "medium",
    points: 15,
  },
  {
    id: "q5",
    text: "What is the chemical symbol for Gold?",
    options: ["Go", "Gd", "Au", "Ag"],
    correctAnswer: 2,
    category: "Science",
    difficulty: "medium",
    points: 15,
  },
  {
    id: "q6",
    text: "Who wrote 'Romeo and Juliet'?",
    options: [
      "Charles Dickens",
      "William Shakespeare",
      "Jane Austen",
      "Mark Twain",
    ],
    correctAnswer: 1,
    category: "Literature",
    difficulty: "easy",
    points: 10,
  },
  {
    id: "q7",
    text: "What is the speed of light in vacuum (approximately)?",
    options: ["300,000 km/s", "150,000 km/s", "450,000 km/s", "600,000 km/s"],
    correctAnswer: 0,
    category: "Science",
    difficulty: "hard",
    points: 20,
  },
  {
    id: "q8",
    text: "Which country has the largest population?",
    options: ["United States", "India", "China", "Indonesia"],
    correctAnswer: 1,
    category: "Geography",
    difficulty: "medium",
    points: 15,
  },
  {
    id: "q9",
    text: "What is the square root of 144?",
    options: ["10", "11", "12", "13"],
    correctAnswer: 2,
    category: "Mathematics",
    difficulty: "easy",
    points: 10,
  },
  {
    id: "q10",
    text: "Who painted the Mona Lisa?",
    options: [
      "Vincent van Gogh",
      "Pablo Picasso",
      "Leonardo da Vinci",
      "Michelangelo",
    ],
    correctAnswer: 2,
    category: "Art",
    difficulty: "easy",
    points: 10,
  },
];

// Mock Quizzes
export const mockQuizzes: Quiz[] = [
  {
    id: "quiz1",
    title: "General Knowledge Challenge",
    description:
      "Test your general knowledge across various topics including science, history, and geography.",
    category: "General",
    difficulty: "easy",
    timeLimit: 10,
    questions: mockQuestions.slice(0, 5),
    totalPoints: 60,
    createdAt: new Date("2024-01-15"),
    isActive: true,
  },
  {
    id: "quiz2",
    title: "Science & Nature",
    description:
      "Explore the wonders of science and nature with these challenging questions.",
    category: "Science",
    difficulty: "medium",
    timeLimit: 15,
    questions: mockQuestions.filter((q) => q.category === "Science"),
    totalPoints: 55,
    createdAt: new Date("2024-02-01"),
    isActive: true,
  },
  {
    id: "quiz3",
    title: "History Trivia",
    description:
      "Journey through time and test your knowledge of historical events.",
    category: "History",
    difficulty: "hard",
    timeLimit: 20,
    questions: mockQuestions.slice(3, 8),
    totalPoints: 75,
    createdAt: new Date("2024-02-10"),
    isActive: true,
  },
  {
    id: "quiz4",
    title: "Quick Fire Round",
    description:
      "Fast-paced quiz with easy questions. Perfect for a quick brain workout!",
    category: "General",
    difficulty: "easy",
    timeLimit: 5,
    questions: mockQuestions.slice(0, 3),
    totalPoints: 30,
    createdAt: new Date("2024-03-01"),
    isActive: true,
  },
  {
    id: "quiz5",
    title: "Arts & Literature",
    description:
      "For the cultured minds. Test your knowledge of art and literature.",
    category: "Arts",
    difficulty: "medium",
    timeLimit: 12,
    questions: mockQuestions.slice(5, 10),
    totalPoints: 65,
    createdAt: new Date("2024-03-15"),
    isActive: false,
  },
];

// Mock Quiz Attempts
export const mockQuizAttempts: QuizAttempt[] = [
  {
    id: "attempt1",
    quizId: "quiz1",
    quizTitle: "General Knowledge Challenge",
    userId: "2",
    answers: [2, 1, 1, 2, 2],
    score: 60,
    totalPoints: 60,
    percentage: 100,
    completedAt: new Date("2024-03-20"),
    timeTaken: 480,
  },
  {
    id: "attempt2",
    quizId: "quiz2",
    quizTitle: "Science & Nature",
    userId: "2",
    answers: [1, 1, 2, 0],
    score: 45,
    totalPoints: 55,
    percentage: 81.8,
    completedAt: new Date("2024-03-18"),
    timeTaken: 720,
  },
  {
    id: "attempt3",
    quizId: "quiz3",
    quizTitle: "History Trivia",
    userId: "2",
    answers: [2, 2, 1, 0, 2],
    score: 55,
    totalPoints: 75,
    percentage: 73.3,
    completedAt: new Date("2024-03-15"),
    timeTaken: 900,
  },
  {
    id: "attempt4",
    quizId: "quiz4",
    quizTitle: "Quick Fire Round",
    userId: "2",
    answers: [2, 1, 0],
    score: 20,
    totalPoints: 30,
    percentage: 66.7,
    completedAt: new Date("2024-03-10"),
    timeTaken: 180,
  },
];

// Mock Leaderboard
export const mockLeaderboard: LeaderboardEntry[] = [
  {
    rank: 1,
    userId: "u1",
    userName: "Alex Champion",
    totalScore: 2450,
    quizzesCompleted: 28,
    averageScore: 87.5,
  },
  {
    rank: 2,
    userId: "u2",
    userName: "Sarah Masters",
    totalScore: 2280,
    quizzesCompleted: 25,
    averageScore: 91.2,
  },
  {
    rank: 3,
    userId: "u3",
    userName: "Mike Scholar",
    totalScore: 2100,
    quizzesCompleted: 24,
    averageScore: 87.5,
  },
  {
    rank: 4,
    userId: "2",
    userName: "John Player",
    totalScore: 1850,
    quizzesCompleted: 22,
    averageScore: 84.1,
  },
  {
    rank: 5,
    userId: "u5",
    userName: "Emma Brainiac",
    totalScore: 1720,
    quizzesCompleted: 20,
    averageScore: 86.0,
  },
  {
    rank: 6,
    userId: "u6",
    userName: "David Genius",
    totalScore: 1580,
    quizzesCompleted: 19,
    averageScore: 83.2,
  },
  {
    rank: 7,
    userId: "u7",
    userName: "Lisa Smarty",
    totalScore: 1420,
    quizzesCompleted: 18,
    averageScore: 78.9,
  },
  {
    rank: 8,
    userId: "u8",
    userName: "Tom Quizzer",
    totalScore: 1280,
    quizzesCompleted: 16,
    averageScore: 80.0,
  },
];

// Mock Players for Admin
export const mockPlayers: User[] = [
  {
    id: "2",
    name: "John Player",
    email: "player@quiz.com",
    role: "player",
    createdAt: new Date("2024-02-15"),
    totalQuizzes: 22,
    averageScore: 84.1,
  },
  {
    id: "u1",
    name: "Alex Champion",
    email: "alex@quiz.com",
    role: "player",
    createdAt: new Date("2024-01-10"),
    totalQuizzes: 28,
    averageScore: 87.5,
  },
  {
    id: "u2",
    name: "Sarah Masters",
    email: "sarah@quiz.com",
    role: "player",
    createdAt: new Date("2024-01-20"),
    totalQuizzes: 25,
    averageScore: 91.2,
  },
  {
    id: "u3",
    name: "Mike Scholar",
    email: "mike@quiz.com",
    role: "player",
    createdAt: new Date("2024-02-01"),
    totalQuizzes: 24,
    averageScore: 87.5,
  },
  {
    id: "u5",
    name: "Emma Brainiac",
    email: "emma@quiz.com",
    role: "player",
    createdAt: new Date("2024-02-10"),
    totalQuizzes: 20,
    averageScore: 86.0,
  },
];

// Dashboard Stats
export const mockDashboardStats = {
  admin: {
    totalPlayers: 156,
    totalQuizzes: 48,
    totalQuestions: 520,
    activeQuizzes: 32,
    averageScore: 76.8,
    quizzesCompletedToday: 24,
    newPlayersThisWeek: 12,
  },
  player: {
    quizzesCompleted: 22,
    totalScore: 1850,
    averageScore: 84.1,
    rank: 4,
    streak: 5,
    quizzesAvailable: 4,
  },
};

// Chart data for analytics
export const monthlyQuizData = [
  { month: "Jan", completed: 120, players: 45 },
  { month: "Feb", completed: 180, players: 62 },
  { month: "Mar", completed: 240, players: 78 },
  { month: "Apr", completed: 310, players: 95 },
  { month: "May", completed: 280, players: 88 },
  { month: "Jun", completed: 350, players: 112 },
];

export const categoryDistribution = [
  { name: "Science", value: 35, fill: "var(--chart-1)" },
  { name: "History", value: 25, fill: "var(--chart-2)" },
  { name: "Geography", value: 20, fill: "var(--chart-3)" },
  { name: "Literature", value: 12, fill: "var(--chart-4)" },
  { name: "Arts", value: 8, fill: "var(--chart-5)" },
];

export const playerScoreHistory = [
  { date: "Week 1", score: 72 },
  { date: "Week 2", score: 78 },
  { date: "Week 3", score: 85 },
  { date: "Week 4", score: 82 },
  { date: "Week 5", score: 88 },
  { date: "Week 6", score: 91 },
];
